drop index if exists Transactions_Type;
drop index if exists Transactions_Hash;
drop index if exists Transactions_Time;
drop index if exists Transactions_BlockHash;
drop index if exists Transactions_Height;
drop index if exists Transactions_String1;
drop index if exists Transactions_String2;
drop index if exists Transactions_String3;
drop index if exists Transactions_String4;
drop index if exists Transactions_String5;
drop index if exists Transactions_Int1;
drop index if exists Transactions_Type_String1_Height;
drop index if exists Transactions_Type_String2_Height;
drop index if exists Transactions_Type_Height_Id;
drop index if exists TxOutput_SpentHeight;
drop index if exists TxOutput_TxHash_Number;
drop index if exists TxOutputs_AddressHash_SpentHeight_Value;
drop index if exists Ratings_Height;
drop index if exists Ratings_Type_Id_Value;
drop index if exists Ratings_Type_Id_Height;


create index if not exists Transactions_Type on Transactions (Type);
create index if not exists Transactions_Hash on Transactions (Hash);
create index if not exists Transactions_Time on Transactions (Time);
create index if not exists Transactions_BlockHash on Transactions (BlockHash);
create index if not exists Transactions_Height on Transactions (Height);
create index if not exists Transactions_String1 on Transactions (String1);
create index if not exists Transactions_String2 on Transactions (String2);
create index if not exists Transactions_String3 on Transactions (String3);
create index if not exists Transactions_String4 on Transactions (String4);
create index if not exists Transactions_String5 on Transactions (String5);
create index if not exists Transactions_Int1 on Transactions (Int1);
create index if not exists Transactions_Type_String1_Height on Transactions (Type, String1, Height, Hash);
create index if not exists Transactions_Type_String2_Height on Transactions (Type, String2, Height, Hash);
create index if not exists Transactions_Type_Height_Id on Transactions (Type, Height, Id);
create index if not exists TxOutput_SpentHeight on TxOutputs (SpentHeight);
create index if not exists TxOutput_TxHash_Number on TxOutputs (TxHash, Number);
create index if not exists TxOutputs_AddressHash_SpentHeight_Value on TxOutputs (AddressHash, SpentHeight, Value);
create index if not exists Ratings_Height on Ratings (Height);
create index if not exists Ratings_Type_Id_Value on Ratings (Type, Id, Value);
create index if not exists Ratings_Type_Id_Height on Ratings (Type, Id, Height desc);