#ifndef POCKETCOIN_CHAINPARAMSSEEDS_H
#define POCKETCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the pocketcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[1] = {

};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x9d,0x5a,0xeb,0x79}, 36060},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x9d,0x5a,0xe4,0x22}, 36060}
};
#endif // POCKETCOIN_CHAINPARAMSSEEDS_H
